version: '3.8'


services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - .:/app
    restart: always
    environment:
      FLASK_APP: app.py 
      FLASK_ENV: development 
      PORT: ${PORT:-5000}
     
